version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    environment:
      DB_HOST: 172.31.47.94
      DB_NAME: cloudlab
      DB_USER: labuser
      DB_PASS: labpass123
      JWT_SECRET: supersecretkey123

  event-service:
    build: ./event-service
    ports:
      - "3002:3002"
    environment:
      DB_HOST: 172.31.47.94
      DB_NAME: cloudlab
      DB_USER: labuser
      DB_PASS: labpass123
      JWT_SECRET: supersecretkey123
      RABBITMQ_URL: amqp://rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy

  notification-service:
    build: ./notification-service
    ports:
      - "3003:3003"
    environment:
      RABBITMQ_URL: amqp://rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy

  event-log:
    build: ./event-log
    ports:
      - "3004:3004"
    environment:
      RABBITMQ_URL: amqp://rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./event-log/logs:/app/logs
